source "https://rubygems.org"
gem "github-pages", group: :jekyll_plugins
gem "jekyll-include-cache", group: :jekyll_plugins
gem "minimal-mistakes-jekyll"
gem "webrick", "~> 1.7"
gem 'liquid', '~> 4.0', '>= 4.0.4'
